### ISSUE TITLE
The Free Starter pack link should not be confusing.

### ISSUE THREAD

**Issue by Benunc** [MediaRon/launch-with-words#1]
Currently, when I click the link from the settings page to "Visit Launch With Words for a free starter pack" I am taken to essentially a sales page for the whole thing. I'm already sold on the whole thing, I'm just here looking for my free download.

I should be taken directly to a free download, with as much populated in the cart as possible, along with some sort of guarantee that the only reason you need my email address is to send me that download or something. 

Just now in my tests, I had to search to figure out how to actually get to the download. 

I'm submitting a PR that changes the URL to go directly to the Free download product, but even better would be a URL that adds the product to the cart and takes me straight there. I feel sure that's possible with EDD, but I have not tried it. 

One pro tip is to use a URL shortner for all of those offsite links so that if you want to change them in the future, you can change them within the shortener service (I use [YOURLS](https://yourls.org)) without having to ship new code to the repo.

**Comment by gidgey** [comment]
Thanks for bringing that up, @Benunc. 
For now I will keep it as is. I want people to read the information on that page and not just "go to cart."

**Comment by Benunc** [comment]
Heads up that you approved the PR that makes this change, after saying that you were not going to make this change!

It's your rodeo, for sure, but as someone who was trying to get to my download as quickly as possible, I was not interested in reading or watching videos. I'd already been sold by the copy on the admin screen. I wanted to skip straight to getting the content.

**Comment by gidgey** [comment]
I added the button. I mean I don't want to manage short links. Thanks, Ben.


Cell 949 370 4059
www.bridgetwillard.com
